### ISSUE TITLE
Segfault in Atom::get_hash() 

### ISSUE THREAD

**Issue by misgeatgit** [opencog/atomspace#1275]
I am getting a segfault while calling  nlp-parse together with ECAN running. Steps I'm following are as follows.
```
opencog> loadmodule ./opencog/attention/libattention.so
opencog> start-ecan
opencog> scm
scm> (use-modules (opencog nlp))
scm> (use-modules (opencog nlp chatbot)) 
scm>(use-modules (opencog nlp relex2logic))
scm> (nlp-start-stimulation 70)
scm> (parse-all nlp-parse "PATH_TO/exp1_insects_sent.txt")
```
exp1_insects_sent.txt is found [here]( https://github.com/misgeatgit/opencog/blob/experiment/experiments/insect-poison/exp1_insects_sent.txt)

Below is Stack trace from gdb. As seen in the stack trace, the handle is valid one but for a reason I don't understand  [get_hash()](https://github.com/opencog/atomspace/blob/master/opencog/atoms/base/Atom.h#L233) function is segfaulting. 
```
#0  opencog::hash_value (h=...) at /home/misgana/OPENCOG/atomspace/opencog/atoms/base/Handle.cc:82
#1  0x00007ffff5f775e4 in operator() () at /home/misgana/OPENCOG/atomspace/opencog/atoms/base/Handle.h:331
#2  _M_hash_code () at /usr/include/c++/6/bits/hashtable_policy.h:1167
#3  std::_Hashtable<opencog::Handle, std::pair<opencog::Handle const, std::shared_ptr<opencog::AttentionValue const> >, std::allocator<std::pair<opencog::Handle const, std::shared_ptr<opencog::AttentionValue const> > >, std::__detail::_Select1st, std::equal_to<opencog::Handle>, std::hash<opencog::Handle>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find (this=this@entry=0x62f438, __k=...) at /usr/include/c++/6/bits/hashtable.h:1292
#4  0x00007ffff5f7b087 in find () at /usr/include/c++/6/bits/unordered_map.h:851
#5  opencog::AttentionBank::get_av(opencog::Handle const&) (this=this@entry=0x62f410, h=...)
    at /home/misgana/OPENCOG/atomspace/opencog/attentionbank/AttentionBank.cc:145
#6  0x00007ffff5f786e9 in opencog::AttentionBank::updateAttentionalFocus(opencog::Handle const&, std::shared_ptr<opencog::AttentionValue const> const&, std::shared_ptr<opencog::AttentionValue const> const&) (
    this=this@entry=0x62f410, h=..., old_av=..., new_av=...)
    at /home/misgana/OPENCOG/atomspace/opencog/attentionbank/AttentionBank.cc:375
#7  0x00007ffff5f7ca52 in opencog::AttentionBank::AVChanged(opencog::Handle const&, std::shared_ptr<opencog::AttentionValue const> const&, std::shared_ptr<opencog::AttentionValue const> const&) (this=this@entry=0x62f410, h=..., 
    old_av=..., new_av=...) at /home/misgana/OPENCOG/atomspace/opencog/attentionbank/AttentionBank.cc:194
#8  0x00007ffff5f7b83c in opencog::AttentionBank::change_av(opencog::Handle const&, std::shared_ptr<opencog::AttentionValue const>) (this=this@entry=0x62f410, h=..., newav=...)
    at /home/misgana/OPENCOG/atomspace/opencog/attentionbank/AttentionBank.cc:95
#9  0x00007ffff5f7b923 in opencog::AttentionBank::set_sti(opencog::Handle const&, double) (this=0x62f410, h=..., 
    stiValue=<optimized out>) at /home/misgana/OPENCOG/atomspace/opencog/attentionbank/AttentionBank.cc:104
#10 0x00007fffd10ff810 in opencog::ImportanceDiffusionBase::tradeSTI (this=this@entry=0x11396e0, event=...)
    at /home/misgana/OPENCOG/opencog/opencog/attention/ImportanceDiffusionBase.cc:182
#11 0x00007fffd10fff1f in opencog::ImportanceDiffusionBase::processDiffusionStack (this=this@entry=0x11396e0)
    at /home/misgana/OPENCOG/opencog/opencog/attention/ImportanceDiffusionBase.cc:486
#12 0x00007fffd11058d8 in opencog::AFImportanceDiffusionAgent::spreadImportance (this=0x11396e0)
    at /home/misgana/OPENCOG/opencog/opencog/attention/AFImportanceDiffusionAgent.cc:73
#13 0x00007fffd1105655 in opencog::AFImportanceDiffusionAgent::run (this=0x11396e0)
    at /home/misgana/OPENCOG/opencog/opencog/attention/AFImportanceDiffusionAgent.cc:56
#14 0x00007ffff7bae193 in opencog::AgentRunnerBase::run_agent (this=this@entry=0x112f810, 
    a=std::shared_ptr (count 5, weak 0) 0x11396e0)
    at /home/misgana/OPENCOG/opencog/opencog/cogserver/server/AgentRunnerBase.cc:123
#15 0x00007ffff7baff82 in opencog::AgentRunnerThread::process_agents_thread (this=0x112f810)
    at /home/misgana/OPENCOG/opencog/opencog/cogserver/server/AgentRunnerThread.cc:131
#16 0x00007ffff729787f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#17 0x00007ffff5b2b184 in start_thread (arg=0x7fffc17fa700) at pthread_create.c:312
#18 0x00007ffff6d25bed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by misgeatgit** [comment]
Resolved by PR https://github.com/opencog/atomspace/pull/1281 .
