### ISSUE TITLE
scheme_eval_h requires 2 arguments

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/atomspace#1771]
Trying to run the python example code form the [atomspace wiki page](https://wiki.opencog.org/w/AtomSpace) leads to the following error:
```
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /tmp/atomspace-master/opencog/scm/opencog/base/core-docs.scm
;;; compiled /home/enoch/.cache/guile/ccache/2.0-LE-8-2.0/tmp/atomspace-master/opencog/scm/opencog/base/core-docs.scm.go
;;; compiling /tmp/atomspace-master/opencog/scm/opencog/base/utilities.scm
;;; compiled /home/enoch/.cache/guile/ccache/2.0-LE-8-2.0/tmp/atomspace-master/opencog/scm/opencog/base/utilities.scm.go
;;; compiling /tmp/atomspace-master/opencog/scm/opencog/base/atom-cache.scm
;;; compiled /home/enoch/.cache/guile/ccache/2.0-LE-8-2.0/tmp/atomspace-master/opencog/scm/opencog/base/atom-cache.scm.go
;;; compiling /tmp/atomspace-master/opencog/scm/opencog/base/apply.scm
;;; compiled /home/enoch/.cache/guile/ccache/2.0-LE-8-2.0/tmp/atomspace-master/opencog/scm/opencog/base/apply.scm.go
;;; compiling /tmp/atomspace-master/opencog/scm/opencog/base/tv.scm
;;; compiled /home/enoch/.cache/guile/ccache/2.0-LE-8-2.0/tmp/atomspace-master/opencog/scm/opencog/base/tv.scm.go
;;; compiling /tmp/atomspace-master/opencog/scm/opencog/base/file-utils.scm
;;; compiled /home/enoch/.cache/guile/ccache/2.0-LE-8-2.0/tmp/atomspace-master/opencog/scm/opencog/base/file-utils.scm.go
;;; compiling /tmp/atomspace-master/opencog/scm/opencog/base/debug-trace.scm
;;; compiled /home/enoch/.cache/guile/ccache/2.0-LE-8-2.0/tmp/atomspace-master/opencog/scm/opencog/base/debug-trace.scm.go
Traceback (most recent call last):
  File "python_example1.py", line 13, in <module>
    a2 = scheme_eval_h('(cog-node \'ConceptNode "Apple")')
  File "opencog/scheme_wrapper.pyx", line 42, in opencog.scheme_wrapper.scheme_eval_h (/tmp/atomspace-master/build/opencog/cython/opencog/scheme_wrapper.cpp:1067)
TypeError: scheme_eval_h() takes exactly 2 positional arguments (1 given)
```

Is there any documentation for the current versions of python functions for dealing with atomspace?

**Comment by StrangeTcy** [comment]
After trying out a few guesses I've found out that the correct syntax would be 
`a2 = scheme_eval_h(asp, '(cog-node \'ConceptNode "Apple")')`

Still, I wonder if it's documented anywhere, and how did I miss it if it is.

**Comment by vsbogd** [comment]
I work on this part of code now, and will add Python docs to methods mentioned.

**Comment by linas** [comment]
FYI, You realize that many versions of unix do an `rm -r /tmp/*` upon reboot, right?

**Comment by vsbogd** [comment]
Fixed code example on wiki https://wiki.opencog.org/w/AtomSpace#Python
