### ISSUE TITLE
crash in pattern matcher

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#204]
Follow-up to bug #165 -- this:
```
(define B 
   (BindLink 
      (VariableList (VariableNode "$A") (VariableNode "$B")) 
      (AndLink
          (VariableNode "$A")
          (VariableNode "$B")
          (EqualLink (VariableNode "$A") (VariableNode "$B"))
      )
      (ListLink (VariableNode "$A") (VariableNode "$B"))))

(cog-bind B)
```

leads to intermittent crashes, probably depending on the atomspace contents.  One stack trace excerpt is this:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7519a03 in _IO_vfprintf_internal (s=s@entry=0x7fffffffaf40, 
    format=<optimized out>, 
    format@entry=0xfbfd70 "Backtrace:\nIn system/repl/repl.scm:\n 142: 19 [start-repl* _ _ _]\n 188: 18 [run-repl* # #<procedure prompting-meta-read (repl)>]\nIn ice-9/boot-9.scm:\n 845: 17 [catch #t ...]\nIn system/vm/trap-state.scm"..., 
    ap=ap@entry=0x7fffffffb928) at vfprintf.c:1661
1661	vfprintf.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7519a03 in _IO_vfprintf_internal (s=s@entry=0x7fffffffaf40, 
    format=<optimized out>, 
    format@entry=0xfbfd70 "Backtrace:\nIn system/repl/repl.scm:\n 142: 19 [start-repl* _ _ _]\n 188: 18 [run-repl* # #<procedure prompting-meta-read (repl)>]\nIn ice-9/boot-9.scm:\n 845: 17 [catch #t ...]\nIn system/vm/trap-state.scm"..., 
    ap=ap@entry=0x7fffffffb928) at vfprintf.c:1661
#1  0x00007ffff75d7235 in ___vsnprintf_chk (
    s=s@entry=0x7fffffffb0b0 "Backtrace:\nIn system/repl/repl.scm:\n 142: 19 [start-repl* _ _ _]\n 188: 18 [run-repl* # #<procedure prompting-meta-read (repl)>]\nIn ice-9/boot-9.scm:\n 845: 17 [catch #t ...]\nIn system/vm/trap-state.scm"..., 
    maxlen=<optimized out>, maxlen@entry=2048, flags=flags@entry=1, 
    slen=slen@entry=2048, 
    format=0xfbfd70 "Backtrace:\nIn system/repl/repl.scm:\n 142: 19 [start-repl* _ _ _]\n 188: 18 [run-repl* # #<procedure prompting-meta-read (repl)>]\nIn ice-9/boot-9.scm:\n 845: 17 [catch #t ...]\nIn system/vm/trap-state.scm"..., 
    format@entry=0x7fffffffb0b0 "Backtrace:\nIn system/repl/repl.scm:\n 142: 19 [start-repl* _ _ _]\n 188: 18 [run-repl* # #<procedure prompting-meta-read (repl)>]\nIn ice-9/boot-9.scm:\n 845: 17 [catch #t ...]\nIn system/vm/trap-state.scm"..., 
    args=args@entry=0x7fffffffb928) at vsnprintf_chk.c:63
#2  0x00007ffff43dd304 in vsnprintf (__ap=0x7fffffffb928, 
    __fmt=0x7fffffffb0b0 "Backtrace:\nIn system/repl/repl.scm:\n 142: 19 [start-repl* _ _ _]\n 188: 18 [run-repl* # #<procedure prompting-meta-read (repl)>]\nIn ice-9/boo---Type <return> to continue, or q <return> to quit--- 
t-9.scm:\n 845: 17 [catch #t ...]\nIn system/vm/trap-state.scm"..., __n=2048, 
    __s=0x7fffffffb0b0 "Backtrace:\nIn system/repl/repl.scm:\n 142: 19 [start-repl* _ _ _]\n 188: 18 [run-repl* # #<procedure prompting-meta-read (repl)>]\nIn ice-9/boot-9.scm:\n 845: 17 [catch #t ...]\nIn system/vm/trap-state.scm"...)
    at /usr/include/x86_64-linux-gnu/bits/stdio2.h:78
#3  opencog::StandardException::parseErrorMessage (this=this@entry=0xf68ca0, 
    fmt=fmt@entry=0xfbfd70 "Backtrace:\nIn system/repl/repl.scm:\n 142: 19 [start-repl* _ _ _]\n 188: 18 [run-repl* # #<procedure prompting-meta-read (repl)>]\nIn ice-9/boot-9.scm:\n 845: 17 [catch #t ...]\nIn system/vm/trap-state.scm"..., 
    ap=ap@entry=0x7fffffffb928, logError=logError@entry=true)
    at /home/linas/src/novamente/src/cogutils-git/opencog/util/exceptions.cc:50
#4  0x00007ffff43dd3ba in opencog::StandardException::parseErrorMessage (
    this=0xf68ca0, 
    trace=0x7ffff48e9fb8 " (/home/linas/src/novamente/src/atomspace-git/opencog/guile/SchemeEval.cc:1079)", 
    msg=0xfc5ce8 "Backtrace:\nIn system/repl/repl.scm:\n 142: 19 [start-repl* _ _ _]\n 188: 18 [run-repl* # #<procedure prompting-meta-read (repl)>]\nIn ice-9/boot-9.scm:\n 845: 17 [catch #t ...]\nIn system/vm/trap-state.scm"..., ap=0x7fffffffb928, 
    logError=<optimized out>)
    at /home/linas/src/novamente/src/cogutils-git/opencog/util/exceptions.cc:66
#5  0x00007ffff43dd4b4 in opencog::RuntimeException::RuntimeException (
    this=0xf68ca0, 
    trace=0x7ffff48e9fb8 " (/home/linas/src/novamente/src/atomspace-git/opencog/guile/SchemeEval.cc:1079)", 
    fmt=0xfc5ce8 "Backtrace:\nIn system/repl/repl.scm:\n 142: 19 [start-repl* _ _ _]\n 188: 18 [run-repl* # #<procedure prompting-meta-read (repl)>]\nIn ice-9/boot-9.scm:\n 845: 17 [catch #t ...]\nIn system/vm/trap-state.scm"...)
    at /home/linas/src/novamente/src/cogutils-git/opencog/util/exceptions.cc:135
#6  0x00007ffff48d4280 in opencog::SchemeEval::apply_tv (this=this@entry=0xfc3f90, 
    func=..., varargs=...)
    at /home/linas/src/novamente/src/atomspace-git/opencog/guile/SchemeEval.cc:1079
#7  0x00007fffed3f9b6c in opencog::EvaluationLink::do_evaluate (as=<optimized out>, 
    gsn=..., args=...)
    at /home/linas/src/novamente/src/atomspace-git/opencog/atoms/execution/EvaluationLink.cc:225
#8  0x00007fffed3fa8be in opencog::EvaluationLink::do_evaluate (
    as=as@entry=0x7fffffffd008, sna=...)
    at /home/linas/src/novamente/src/atomspace-git/opencog/atoms/execution/EvaluationLink.cc:167
#9  0x00007fffed3fae9a in opencog::EvaluationLink::do_evaluate (
    as=as@entry=0x7fffffffd008, execlnk=...)
    at /home/linas/src/novamente/src/atomspace-git/opencog/atoms/execution/EvaluationLink.cc:133

```

**Comment by linas** [comment]
This is fixed by https://github.com/opencog/cogutils/pull/17

This is EXACTLY the same kind of stack trace that would be seen.
