### ISSUE TITLE
Unicode not escaped to string in python binding

### ISSUE THREAD

**Issue by alexander-gabriel** [opencog/atomspace#2522]
```
Traceback (most recent call last):
  File "example2.py", line 17, in <module>
    rbs = ConceptNode("deduction-rule-base")
  File "core_types.pyx", line 17, in opencog.type_constructors.ConceptNode (/home/rasberry/git/atomspace/build/opencog/cython/opencog/type_constructors.cpp:2282)
  File "opencog/utilities.pyx", line 83, in opencog.utilities.add_node (/home/rasberry/git/atomspace/build/opencog/cython/opencog/utilities.cpp:2402)
  File "opencog/nameserver.pyx", line 83, in opencog.atomspace.create_python_value_from_c_value (/home/rasberry/git/atomspace/build/opencog/cython/opencog/atomspace.cpp:2428)
  File "opencog/nameserver.pyx", line 32, in opencog.atomspace.get_type (/home/rasberry/git/atomspace/build/opencog/cython/opencog/atomspace.cpp:1836)
TypeError: Expected str, got unicode

```

```
#!/usr/bin/env python

from opencog.type_constructors import *
from opencog.utilities import initialize_opencog
from opencog.atomspace import AtomSpace


if __name__ == '__main__':
    atomspace = AtomSpace()
    initialize_opencog(atomspace)
    ConceptNode("bla")
```

**Comment by alexander-gabriel** [comment]
This is in python 2.7

**Comment by alexander-gabriel** [comment]
```
#!/usr/bin/env python

from opencog.type_constructors import *
from opencog.utilities import initialize_opencog
from opencog.atomspace import AtomSpace, types


if __name__ == "__main__":
    atomspace = AtomSpace()
    initialize_opencog(atomspace)
    atomspace.add_node(types.ConceptNode, "bla")
    # ConceptNode("bla")
```
this works.

**Comment by alexander-gabriel** [comment]
Also happens when getting outgoing sets after reasoning:

```
  File "/home/rasberry/catkin_ws/src/rasberry_hri/src/bdi/goals.py", line 314, in find_instances
    for setlink in results.get_out():
  File "opencog/atom.pyx", line 91, in opencog.atomspace.Atom.get_out (/home/rasberry/git/atomspace/build/opencog/cython/opencog/atomspace.cpp:9293)
  File "opencog/atomspace_details.pyx", line 22, in opencog.atomspace.convert_handle_seq_to_python_list (/home/rasberry/git/atomspace/build/opencog/cython/opencog/atomspace.cpp:3651)
  File "opencog/nameserver.pyx", line 87, in opencog.atomspace.create_python_value_from_c_value (/home/rasberry/git/atomspace/build/opencog/cython/opencog/atomspace.cpp:2537)
  File "opencog/nameserver.pyx", line 32, in opencog.atomspace.get_type (/home/rasberry/git/atomspace/build/opencog/cython/opencog/atomspace.cpp:1836)
TypeError: Expected str, got unicode
```

**Comment by linas** [comment]
I cannot test python2; can you try the following patch, see if it works:
```
--- a/opencog/cython/opencog/utilities.pyx
+++ b/opencog/cython/opencog/utilities.pyx
@@ -76,8 +76,8 @@ def add_node(Type t, atom_name, TruthValue tv=None):
     """
     Add Node to the atomspace from the current context
     """
-    cdef string name = atom_name.encode('UTF-8')
-    cdef cHandle result = c_add_node(t, name)
+#    cdef string name = atom_name.encode('UTF-8')
+    cdef cHandle result = c_add_node(t, atom_name)
 
     if result == result.UNDEFINED: return None
     atom = create_python_value_from_c_value(<cValuePtr&>result)
```

**Comment by linas** [comment]
Also -- which cython version are you using? I have a vague feeling that newer cython versions won't have this bug .. !?

**Comment by alexander-gabriel** [comment]
Cython version 0.23.4
ships with 16.04
I'll give your patch a try now. stay tuned

**Comment by linas** [comment]
My patch is wrong, that's not your bug... I failed to read your error message...

**Comment by linas** [comment]
Try this patch instead:
```
--- a/opencog/cython/opencog/nameserver.pyx
+++ b/opencog/cython/opencog/nameserver.pyx
@@ -80,11 +80,11 @@ cdef create_python_value_from_c_value(cValuePtr& value):
         return clazz(ptr_holder = ptr_holder)
 
     # For handling the children types of TruthValue.
-    if is_a(get_type(type_name), types.TruthValue):
+    if is_a(type, types.TruthValue):
         return TruthValue(ptr_holder = ptr_holder)
 
     # For handling the children types of Atom.
-    if is_a(get_type(type_name), types.Atom):
+    if is_a(type, types.Atom):
         return Atom(ptr_holder = ptr_holder)
 
     raise TypeError("Python API for " + type_name + " is not implemented yet")
```

**Comment by linas** [comment]
I'm applying the above patch anyway in #2523, because it's obviously the right thing to do, irrespective of this bug. But based on your error messages, I think it also fixes your bug.

**Comment by alexander-gabriel** [comment]
yes that does the trick. but could you rename 'type' to something else '_type' or so...as 'type' is a function in python and you're overwriting that.

**Comment by alexander-gabriel** [comment]
hrm, maybe we should have unit tests running in python 2.

**Comment by linas** [comment]
We had that, for a while-ish. However, python2 hit EOL on January 1 this year, ... If it just happens to work, OK, but adding extra complexity to support it is a bad idea.

**Comment by linas** [comment]
https://www.python.org/doc/sunset-python-2/

**Comment by linas** [comment]
Closing, I assume it all works now.
