### ISSUE TITLE
Persistance API cannot load an Atom which has double quotes inside name

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#2817]
`Sexpr::encode_atom` doesn't escape double quotes inside name of the atom. Thus `(ConceptNode "\"CC\"")` will be encoded as `(ConceptNode ""CC"")`. Such atom will break loading procedure because first pair of quotes will be decoded as empty name:
```
Traceback (most recent call last):
  File "./demo_using_db.py", line 48, in <module>
    load_atomspace(ac.atomspace)
  File "./demo_using_db.py", line 29, in load_atomspace
    ''')
  File "scheme.pyx", line 44, in opencog.scheme.scheme_eval
RuntimeError: Python-Scheme Wrapper: Failed to execute '
        (use-modules (opencog))
        (use-modules (opencog persist))
        (use-modules (opencog persist-rocks))
        (define sto (RocksStorageNode "rocks:///tmp/foo.rdb/"))
        (cog-open sto)
        (load-atomspace)
        (cog-close sto)
    '
Backtrace:
           6 (apply-smob/1 #<catch-closure face020>)
           5 (apply-smob/1 #<catch-closure fadee20>)
In ice-9/boot-9.scm:
   2312:4  4 (save-module-excursion #<procedure fad37c0 at ice-9/eva…>)
In ice-9/eval-string.scm:
     38:6  3 (read-and-eval #<input: string fa58620> #:lang _)
In unknown file:
           2 (opencog-extension dflt-load-atomspace ())
In ice-9/boot-9.scm:
   751:25  1 (dispatch-exception 0 C++-EXCEPTION ("dflt-load-atom…" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure fadede0> C++-EXCEPTION "…" …)

ERROR: In procedure apply-smob/1:
In procedure dflt-load-atomspace: Syntax error at line 0 Unexpected text: >>CC"")<<
Function args:
()
ABORT: C++-EXCEPTION
 (/home/opencog/projects/opencog/atomspace/opencog/cython/opencog/PyScheme.cc:63)
```

**Comment by linas** [comment]
Yep! Do you want to fix this or should I?

**Comment by linas** [comment]
never mind, I have a fix. Pushing. Thanks for pointing this out!

**Comment by vsbogd** [comment]
Thanks @linas, but I believe we also need to unescape it when reading.

**Comment by linas** [comment]
Still working on it. It touches more code than expected. I pushed a new branch just now.

**Comment by linas** [comment]
Could I get you to test embedded back-slashes? I think it should all work, but I'm trying to share the work...

**Comment by vsbogd** [comment]
Sure, I can test it tomorrow morning do you have branch?

**Comment by linas** [comment]
branch `escape-quotes` it will be in the pull request in a few minutes

**Comment by linas** [comment]
Hmm pull req #2818 has the fixes, except that cython now fails for me:
```
$ nosetests3 -vs ./tests/cython/utilities/
test_fast_load (test_utilities.UtilitiesTest) ... FAIL
```
Oddly enough, it passes in circleci...

**Comment by linas** [comment]
There are almost surely bugs involving embedded open and close parens. Ouch.
