### ISSUE TITLE
Segafault in URE-fc

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#909]
@ngeiswei The segfault occurs with deduction-rule. Running `(cog-bind deduction-inheritance-rule)` doesn't cause any issue. Details and steps follow. 

1. Go under `<OPENCOG_ROOT>/opencog/nlp`
2. Run the test file (see below)

### Content of test file
```scheme
(use-modules (opencog))
(use-modules (opencog atom-types))
(use-modules (opencog nlp))
(use-modules (opencog nlp chatbot))
(use-modules (opencog nlp chatbot-psi))
(use-modules (opencog rule-engine))

;; -----------------------------------------------------------------------------
;; Helper functions
(define (last-interp)
    (car (parse-get-interp (car (sentence-get-parses (get-last-said-sent))))))

(define (last-r2l) (interp-get-r2l-outputs (last-interp)))

(define (chat-inputs)
    (define result  '())
    (chat "Socrates is a man")
    (set! result (append result (last-r2l)))
    (chat "Men breathe air")
    (set! result (append result (last-r2l)))
    result
)

;; -----------------------------------------------------------------------------
;; Configure rule-base
(define rb (ConceptNode "rb"))

(define (configure-pln)
    (load-from-path "opencog/pln/rules/formulas.scm")
    (load-from-path "opencog/pln/rules/deduction-rule.scm")

    (ure-define-rbs rb 1)
    (ure-set-fuzzy-bool-parameter rb "URE:attention-allocation" 0)
    (ure-define-add-rule rb "deduction-inheritance-rule"
        deduction-inheritance-rule .8)
)

;; -----------------------------------------------------------------------------
;; Reproduce segfault
(configure-pln)
(cog-fc (Set) rb (Set (chat-inputs)))
```

### Backtrace
```
Program received signal SIGSEGV, Segmentation fault.
0x00007f4140f06766 in opencog::ForwardChainer::apply_rule(opencog::Handle const&)::{lambda(opencog::AtomSpace&, std::vector<opencog::Handle, std::allocator<opencog::Handle> >&)#1}::operator()(opencog::AtomSpa
ce&, std::vector<opencog::Handle, std::allocator<opencog::Handle> >&) const [clone .isra.54.97088] () at /home/amen/hansonrobotics/opencog/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:397
397                         if (t == LIST_LINK)
(gdb) bt
#0  0x00007f4140f06766 in opencog::ForwardChainer::apply_rule(opencog::Handle const&)::{lambda(opencog::AtomSpace&, std::vector<opencog::Handle, std::allocator<opencog::Handle> >&)#1}::operator()(opencog::Ato
mSpace&, std::vector<opencog::Handle, std::allocator<opencog::Handle> >&) const [clone .isra.54.97088] ()
    at /home/amen/hansonrobotics/opencog/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:397
#1  0x00007f4140f1504a in opencog::ForwardChainer::apply_rule (this=this@entry=0x7ffd24f93020, rhandle=...)
    at /home/amen/hansonrobotics/opencog/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:407
#2  0x00007f4140f1156b in opencog::ForwardChainer::apply_all_rules (this=0x7ffd24f93020) at /home/amen/hansonrobotics/opencog/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:161
#3  0x00007f4140f11bb5 in opencog::ForwardChainer::do_chain (this=this@entry=0x7ffd24f93020) at /home/amen/hansonrobotics/opencog/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:135
#4  0x00007f4140f163a4 in opencog::InferenceSCM::do_forward_chaining (this=<optimized out>, hsource=..., rbs=..., hfocus_set=...)
    at /home/amen/hansonrobotics/opencog/atomspace/opencog/rule-engine/InferenceSCM.cc:79
#5  0x00007f4140f01f33 in opencog::SchemePrimitive<opencog::InferenceSCM>::invoke(scm_unused_struct*) [clone .local.126] (this=0x1e9f6d0, args=0x392a910)
    at /home/amen/hansonrobotics/opencog/atomspace/opencog/guile/SchemePrimitive.h:374
#6  0x00007f414cb61af8 in opencog::PrimitiveEnviron::do_call (sfe=0x2941e90, arglist=0x392a910) at /home/amen/hansonrobotics/opencog/atomspace/opencog/guile/SchemePrimitive.cc:150
#7  0x00007f414fb3d12a in ?? () from /usr/lib/libguile-2.0.so.22
#8  0x00007f414fb3d13f in ?? () from /usr/lib/libguile-2.0.so.22
#9  0x00007f414fabfdc3 in scm_primitive_eval () from /usr/lib/libguile-2.0.so.22
#10 0x00007f414fabfe23 in scm_eval () from /usr/lib/libguile-2.0.so.22
#11 0x00007f414fb0e3bd in scm_shell () from /usr/lib/libguile-2.0.so.22
#12 0x00007f414fadc42d in ?? () from /usr/lib/libguile-2.0.so.22
#13 0x00007f414fab62ca in ?? () from /usr/lib/libguile-2.0.so.22
#14 0x00007f414fb47c00 in ?? () from /usr/lib/libguile-2.0.so.22
#15 0x00007f414fabf863 in scm_call_4 () from /usr/lib/libguile-2.0.so.22
#16 0x00007f414fab69ff in ?? () from /usr/lib/libguile-2.0.so.22
#17 0x00007f414fab6a95 in scm_c_with_continuation_barrier () from /usr/lib/libguile-2.0.so.22
#18 0x00007f414fb2f78c in ?? () from /usr/lib/libguile-2.0.so.22
#19 0x00007f414f224fe2 in GC_call_with_stack_base () from /usr/lib/x86_64-linux-gnu/libgc.so.1
#20 0x00007f414fb2fb48 in scm_with_guile () from /usr/lib/libguile-2.0.so.22
---Type <return> to continue, or q <return> to quit---
#21 0x00007f414fadc5c5 in scm_boot_guile () from /usr/lib/libguile-2.0.so.22
#22 0x0000000000400c04 in ?? ()
#23 0x00007f414f499f45 in __libc_start_main (main=0x400b90, argc=1, argv=0x7ffd24f94228, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd24f94218) at libc-start.c:287
#24 0x0000000000400c77 in ?? ()
```

**Comment by ngeiswei** [comment]
@AmeBel I can reproduce that indeed. Do you know since which commit this started failing?

**Comment by ngeiswei** [comment]
Report of my current bisective search on the atomspace repo.

Commits 1342d93, 5f2905a and 648e479 all have the same bug. Commit fc594d6 crashes with a different bt:
```
#0  0x00007fafda36d726 in opencog::TargetSet::emplace (this=0x69decf0, h=..., hvardecl=...) at /usr/include/c++/4.8/bits/stl_tree.h:1158
```
the fact that it crashes on the TargetSet which is used by the BackwardChainer is very weird, but anyway, it's likely a unrelated old bug.

**Comment by AmeBel** [comment]
The r2l-mode of the ure-fc had been in use for more than a year, so it hard to tail.  If it helps, don't have issues with a rulebase containing evaluation-to-member-1-rule, evaluation-to-member-2-rule, member-to-inheritance-rule, abduction-inheritance-rule.

**Comment by ngeiswei** [comment]
I tried more bisect search but I can't compile before 1f4fb45 due to cogutils being incompatible, I could persist of course but I don't think this road is gonna be very fruitful so I'm switching strategy and going into debug mode. If you have any other clue or idea they are welcome.

**Comment by ngeiswei** [comment]
I don't think it is tied to the forward chainer. Sometimes it crashes before ForwardChainer is at all instantiated. I don't know where it comes from though. Still searching...

**Comment by ngeiswei** [comment]
I found what causes the ForwardChainer to crash. The rule application over search focus set return a solution with a null atom.
```
[FINE] [ForwardChainer] [0x7ffea7a642f0] result (from _search_forcus_set) = size = 1
atom[0]:
nullatom
```
I don't know what is causing that yet.

**Comment by ngeiswei** [comment]
Just needed a conditional to avoid adding undefined handles in the resulting inferences over the focus set.

**Comment by AmeBel** [comment]
Thanks
