### ISSUE TITLE
crash while loading example.

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#983]
Loading the example code in `examples/pattern-matcher/deduction-engine.scm` results in a crash.  A partial stack trace is:
```
#0  0x00007fffed80e4a5 in std::__shared_ptr<opencog::Atom, (__gnu_cxx::_Lock_policy)2>::operator=(std::__shared_ptr<opencog::Atom, (__gnu_cxx::_Lock_policy)2> const&) () at /usr/include/c++/6/bits/shared_ptr_base.h:870
#1  std::shared_ptr<opencog::Atom>::operator=(std::shared_ptr<opencog::Atom> const&) () at /usr/include/c++/6/bits/shared_ptr.h:93
#2  opencog::Handle::operator=(opencog::Handle const&) ()
    at /atomspace-git/opencog/atoms/base/Handle.h:102
#3  opencog::PatternLink::unbundle_clauses(opencog::Handle const&) (
    this=this@entry=0x555555f86060, hbody=...)
    at /atomspace-git/opencog/atoms/pattern/PatternLink.cc:322
#4  0x00007fffed808945 in opencog::PatternLink::init() (
    this=this@entry=0x555555f86060)
    at /atomspace-git/opencog/atoms/pattern/PatternLink.cc:134
#5  0x00007fffed80eb86 in opencog::PatternLink::PatternLink(unsigned short, std::vector<opencog::Handle, std::allocator<opencog::Handle> > const&, std::shared_ptr<opencog::TruthValue const>, std::shared_ptr<opencog::AttentionValue const>)
    (this=this@entry=0x555555f86060, t=t@entry=51, hseq=..., tv=..., av=...)
    at /atomspace-git/opencog/atoms/pattern/PatternLink.cc:272
```

**Comment by linas** [comment]
Still crashing, with more-or-less same stack trace
```
#0  0x00007fffecc2dbed in opencog::PatternLink::unbundle_clauses (
    this=this@entry=0x555555f92fc0, hbody=...)
    at /atomspace-git/opencog/atoms/pattern/PatternLink.cc:307
#1  0x00007fffecc30425 in opencog::PatternLink::init (
    this=this@entry=0x555555f92fc0)
    at /atomspace-git/opencog/atoms/pattern/PatternLink.cc:134
#2  0x00007fffecc30f4a in opencog::PatternLink::PatternLink (
    this=0x555555f92fc0, t=<optimized out>, hseq=..., tv=..., av=...)
    at /atomspace-git/opencog/atoms/pattern/PatternLink.cc:272
#3  0x00007fffecc3113c in __gnu_cxx::new_allocator<opencog::PatternLink>::construct<opencog::PatternLink, unsigned short&, std::vector<opencog::Handle, std::allocator<opencog::Handle> > const&> (__p=0x555555f92fc0, this=<optimized out>)
    at /usr/include/c++/6/ext/new_allocator.h:120
#4  std::allocator_traits<std::allocator<opencog::PatternLink> >::construct<opencog::PatternLink, unsigned short&, std::vector<opencog::Handle, std::allocator<opencog::Handle> > const&> (__p=<optimized out>, __a=...)
    at /usr/include/c++/6/bits/alloc_traits.h:455

```

**Comment by linas** [comment]
Its a null-pointer exception:
```
print hbody
$1 = (const opencog::Handle &) @0x555555f93080: {
  _ptr = std::shared_ptr (empty) 0x0, 
  static NULL_POINTER = std::shared_ptr (empty) 0x0, 
  static INVALID_HASH = 18446744073709551615, static UNDEFINED = {
    _ptr = std::shared_ptr (empty) 0x0, 
    static NULL_POINTER = std::shared_ptr (empty) 0x0, 
    static INVALID_HASH = 18446744073709551615, 
    static UNDEFINED = <same as static member of an already seen type>}}
```

**Comment by linas** [comment]
still crashing.

**Comment by linas** [comment]
closing, fixed in commit https://github.com/opencog/atomspace/commit/bcdbaae622db9914fb5d8d47e9f59d0348fbbf87
